### ISSUE TITLE
FindOneById returns null

### ISSUE THREAD

**Issue by antonbrams** [GraphQLGuide/apollo-datasource-mongodb#11]
what could be the reasons if findOneById returns nulll?

```
const {model, Schema} = require('mongoose')
const {MongoDataSource} = require('apollo-datasource-mongodb')

module.exports = new class extends MongoDataSource {
    get (ID) {
        return this.findOneById(ID)
    }
}(model('Item', new Schema ({
    name : {
        type : String, 
        required : true
    }
})))
```

a classic approach with `this.model.findOne({_id : ID})`, as well other mongodb funcs working good

**Comment by lorensr** [comment]
Perhaps try creating the model inside the `dataSources` function? Otherwise, look for differences between how you're doing it and the test does it: https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/__tests__/datasource.test.js#L78-L83

**Comment by antonbrams** [comment]
is there any difference? I've just not using steps in between that doesn't contribute for the general idea :) If the instance extended from MongoDataSource accepts the db model as a parameter in a constructor, well... here it is ))

**Comment by lorensr** [comment]
The test calls `.initialize()`?

**Comment by 9at8** [comment]
@antonbrams Are you using `findOneById('some id')` or `findOneById(ObjectId('some id'))`?

In other words, are you using strings?

**Comment by 9at8** [comment]
My bad, ignore that PR mention pls :sweat_smile:

**Comment by antonbrams** [comment]
> @antonbrams Are you using `findOneById('some id')` or `findOneById(ObjectId('some id'))`?
> 
> In other words, are you using strings?

i'm using strings, yes :)

**Comment by lorensr** [comment]
The function only takes ObjectIds, thought adding strings might be a good PR

**Comment by alishi973** [comment]
Same issue with ``findOneById``

**Comment by 9at8** [comment]
Closing as `findOneById` requires passing in an `ObjectId` and not a `string`

Solution: Use `findOneById(ObjectId('the id'))` instead of `findOneById('the id')`
