### ISSUE TITLE
Any sample code as starter on how to use this package?

### ISSUE THREAD

**Issue by miliu99** [GraphQLGuide/apollo-datasource-mongodb#12]
I spent quite a bit time trying to make it connect to my mongodb but failed. Is there any sample code as starter to show how to use this package? For example, how do you connect to your db for the given url and how do you specify the collection in Datasource contructor. You mentioned using db.collection('users'), what is db here?

**Comment by lorensr** [comment]
Hi, I updated the README for you 😊

![image](https://user-images.githubusercontent.com/251288/76693268-a1625800-6638-11ea-83b6-136daefe7839.png)

**Comment by miliu99** [comment]
Thanks for your response. Did you try out this code? I believe I tried it yesterday and got an error saying client must be connected first to get db. Anyway, after struggling a couple of hours, I gave up. Instead, I now use DataSource with mongoose directly. It turns out it's much simpler and it also gives me much more control.

**Comment by lorensr** [comment]
Ah! Sorry, I forgot the `.connect()`, thank you!
