### ISSUE TITLE
this.collections.insertOne's document argument is an entire schema

### ISSUE THREAD

**Issue by jblevins1991** [GraphQLGuide/apollo-datasource-mongodb#21]
Right now if you look at [insertOne](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#insertOne)'s documentation, the doc argument is the document to insert. In your index.d.ts file the doc argument is an entire schema. This does not align with the spec for `insertOne`.

insertOne from index.d.ts:
```
insertOne(docs: OptionalId<TSchema>, callback: MongoCallback<InsertOneWriteOpResult<WithId<TSchema>>>): void;
    insertOne(docs: OptionalId<TSchema>, options?: CollectionInsertOneOptions): Promise<InsertOneWriteOpResult<WithId<TSchema>>>;
    insertOne(docs: OptionalId<TSchema>, options: CollectionInsertOneOptions, callback: MongoCallback<InsertOneWriteOpResult<WithId<TSchema>>>): void;
```

**Comment by 9at8** [comment]
I believe you're looking at types coming from [@types/mongodb](https://www.npmjs.com/package/@types/mongodb)

**Comment by 9at8** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L1114

**Comment by jblevins1991** [comment]
You are correct. ✌️
