### ISSUE TITLE
How to use other Model in data source?

### ISSUE THREAD

**Issue by thearabbit** [GraphQLGuide/apollo-datasource-mongodb#24]
I tried to use `mongoose`
```js
// Model
const Model1 = mongoose.model('col1', Schema1)
const Model2 = mongoose.model('col2', Schema2)


// Data source
export default class Data1 extends MongoDataSource {
  getData1(name) {
    // How to use `Model2`
    return this.model.findOne({ name: name })
  }
}
........................

// Apollo server
...........
dataSources: () => ({
    data1: new Data1(Model1),
    data2: new Data2(Model2),
  }),
```
How to use `Model2` in DataSource1 (Data1)?

**Comment by lorensr** [comment]
For model methods, feel free to just import Model2. For data source methods (like `data2.findOneById()`), I'm not sure! Haven't seen an established best practice for this. The two solutions that come to mind are:

1. Moving logic to the resolver, which can call methods on both `data1` and `data2`
2. Passing `data2` as an argument to a `data1` method, like in the resolver: `data1.getData1('rabbit', data2)`

**Comment by thearabbit** [comment]
Thanks for your reply.
Excuse me, which one better for ???

1- Use `Logic API` directly on the resolver (Import ....)
2- Use `Logic API` from data source (Apollo Server

**Comment by lorensr** [comment]
Of the two solutions I mentioned, I'm not sure which is better.

**Comment by 9at8** [comment]
You might be able to use context inside the getData method in the Data1 class.

```js
class Data1 extends DataSource {
  getData(x) {
    this.context.dataSources.data2.getData(x)
  }
}
```

**Comment by lorensr** [comment]
Oh yeah! That seems better ☺️

**Comment by thearabbit** [comment]
Very thanks again 👍
