### ISSUE TITLE
Plans to add more to API?

### ISSUE THREAD

**Issue by Nachlawi** [GraphQLGuide/apollo-datasource-mongodb#25]
Are there plans to add more to the API such as finding by more than id?

Maybe an option to find and findOne which accepts an object as the criteria, e.g.

`this.find({ datetime: 1587036888 }, { ttl })`
and 
`this.findOne({ datetime: 1587036888 }, { ttl })`

Also there are other useful methods like `findOneAndUpdate`?

**Comment by lorensr** [comment]
No plans atm. You're welcome to contribute to #1 or #2, and I'd review a PR. Otherwise, the full Mongo API is available under `this.collection`.
