### ISSUE TITLE
Data insert

### ISSUE THREAD

**Issue by tpiros** [GraphQLGuide/apollo-datasource-mongodb#3]
I was wondering how to insert data?.

Also, FYI, the example that uses the `updateOne` method is failing: `users.updateOne is not a function`. Based on this I wanted to use `users.insertOne` but that fails as well of course.

**Comment by lorensr** [comment]
Released `v0.1.0` with a new API. In this example:

https://github.com/GraphQLGuide/apollo-datasource-mongodb#usage

`this.users` is the collection reference, so eg `this.users.updateOne({_id: 'foo, { $set: { name: 'me' }}})`
