### ISSUE TITLE
Basic usage in Typescript

### ISSUE THREAD

**Issue by luciomr** [GraphQLGuide/apollo-datasource-mongodb#31]
I'm trying to use the package in a typescript project. I attempted to use the code described in the Basic Usage section in a .ts file verbatim:

Users.ts
```
import { MongoDataSource } from 'apollo-datasource-mongodb'

export default class Users extends MongoDataSource {
  getUser(userId) {
    return this.findOneById(userId)
  }
} 
```
and later on import it and use it as a data source:

index.ts
```
import Users from './data-sources/Users.js'
...
const server = new ApolloServer({
  ...
  dataSources: () => ({
    users: new Users(client.db().collection('users'))
  })
})
```

But I am getting errors that keep the code from compiling.

- Users.ts my editor (vscode) reports: `Generic type 'MongoDataSource<TData, TContext>' requires between 1 and 2 type arguments.ts(2707)` on MongooseDataSource when I am extending the class.
- index.ts: my editor reports `Expected 0 arguments, but got 1.ts(2554)` on `client.db().collection('users')`
- On compiling, get: 
```
../src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:34:7 - error TS2322: Type '() => { users: Users; }' is not assignable to type '() => DataSources<object>'.
  Type '{ users: Users; }' is not assignable to type 'DataSources<object>'.
    Property 'users' is incompatible with index signature.
      Type 'Users' has no properties in common with type 'DataSource<object>'.

34       dataSources: () => ({
         ~~~~~~~~~~~

  node_modules/apollo-server-core/dist/graphqlOptions.d.ts:24:5
    24     dataSources?: () => DataSources<TContext>;
           ~~~~~~~~~~~
    The expected type comes from property 'dataSources' which is declared here on type 'ApolloServerExpressConfig & { cors?: boolean | CorsOptions | undefined; onHealthCheck?: ((req: Request<ParamsDictionary, any, any, ParsedQs>) => Promise<...>) | undefined; }'
src/index.ts:35:31 - error TS2554: Expected 0 arguments, but got 1.

35         users: new Users(client.db().collection("users")),
```

I didn't go farther in the example code because of these issues. 

Are there any examples with TypeScript code for the basic usage or could you point me in the right direction on how to fix the issues I am having?

Thanks in advance.

**Comment by haydenhancock** [comment]
Same issue here.

**Comment by luciomr** [comment]
I decided to drop the use of this package (and datasources altogether) and implement the logic using mongoose straight on the resolvers(queries/mutations). 

If it is of any help, @haydenhancock ,  the following code was compiling for me:
User.ts:
```
import { MongoDataSource } from "apollo-datasource-mongodb"
import { ObjectId } from "mongodb"

export default class Users<TData> extends MongoDataSource<TData> {

    async getUser(id: ObjectId) {

        return await this.findOneById(id);

    }
}
```
main.ts:
```
     resolvers: {
        Query: {
          getUser: (_, { id }, { dataSources }) => 
            dataSources.Users.getUser({ id: id }),
        },
      ...
      dataSources: () => ({
        ObjectACL: new Users(client.db().collection('users')),
      }),
```

Inside getUser() I was able to access the collection with `this.collection`, but for some reason the methods that the mongo mongo client has to find documents in the collection didn't work inside the datasource code. I think the datasource disables them somehow, because I was able to use them in main.ts .

**Comment by 9at8** [comment]
@haydenhancock @luciomr Sorry for the late response 🙈 This is the collect way to use it in TypeScript. I will update the readme to reflect the change.

```typescript
interface UserCollection {
  _id: ObjectId
  username: string
  password: string
}

class UserDataSource extends MongoDataSource<UserCollection, Context> {
  findUserByUsername(username: string) {
    return this.collection.findOne({username})
  }
}
```

The reason you have to create the `UserCollection` interface/type is so that `this.collection` gets specialized with the correct types.
