### ISSUE TITLE
I do not get MongoDataSource.initialize

### ISSUE THREAD

**Issue by hk86** [GraphQLGuide/apollo-datasource-mongodb#32]
I do not understand MongoDataSource.initialize 

```
  initialize({ context, cache } = {}) {
    this.context = context

    const methods = createCachingMethods({
      collection: this.collection,
      cache: cache || new InMemoryLRUCache()
    })

    Object.assign(this, methods)
  }
```

I would expect to see 

```
    const methods = createCachingMethods({
      collection: this.collection,
      cache: cache || new InMemoryLRUCache()
    })

    Object.assign(this, methods)
```

in the constructor. To my understanding `initialize` is called on each request. The code from above I would want to call only once.

**Comment by lorensr** [comment]
A new `MongoDataSource` is created for each request, so moving to constructor wouldn't change how often it runs. Also, Apollo Server gives the cache to `initialize()`—we don't have access to it in the constructor.
