### ISSUE TITLE
await cache set

### ISSUE THREAD

**Issue by baileywall** [GraphQLGuide/apollo-datasource-mongodb#35]
Hi, I was getting a fair number of floating "UnhandledPromiseRejectionWarning: ReplyError: ERR invalid expire time in set" without a stack trace when trying to set {ttl: 0} on a call to findOneById with Redis as my cache.

I added an await to cache.js:

`      if (Number.isInteger(ttl)) {
        // https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-caching#apollo-server-caching
        await cache.set(key, JSON.stringify(doc), {
          ttl
        });
      }`

and then was able to see the stack trace.

Thanks!

**Comment by lorensr** [comment]
Thanks for the info—I just updated the readme to say `ttl` must be positive. I think we might not want to await there for performance, since it would delay returning the doc.
