### ISSUE TITLE
Are Transactions possible

### ISSUE THREAD

**Issue by dragonfriend0013** [GraphQLGuide/apollo-datasource-mongodb#39]
Since this library is initialized using a collection, are Transactions using multiple collections not possible?

**Comment by lorensr** [comment]
Still possible, this library just adds a couple methods. You wouldn’t use
them during a transaction.

**Comment by dragonfriend0013** [comment]
based on the code, the datasource is initialized with a collection, not a database or client.  transactions are done at the database(s) level, not the collection level.

**Comment by lorensr** [comment]
You aren't limited to using `this.collection` in your datasource
methods—you can also import and use the database client / other
collections.
