### ISSUE TITLE
Replace dynamic collection property name

### ISSUE THREAD

**Issue by sbrichardson** [GraphQLGuide/apollo-datasource-mongodb#4]
At first glance, it seems you could accidentally overwrite a class method or other info if a collection name matches an existing class property? Probably rare or I could also be wrong.

For example (haven’t tested) if you have a collection called “initialize”, “collectionName”, or “context” etc.

The [constructor code](https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/datasource.js#L20) referring to:

`this[this.collectionName] = collection[this.collectionName]`

If so, maybe storing it to a collection property etc?

**Comment by lorensr** [comment]
Hah, yes that would be a problem. I think rare as well 😊. Could blacklist `initialize` etc and do a runtime check in the constructor. I wonder which of these APIs people would like more:

```js
// current
this.users.findOne()

// proposed
this.collection.findOne()
```

**Comment by sbrichardson** [comment]
Difficult to say since users (or Apollo upstream) could extend the class in any way, (storing custom properties etc) I understand the benefit of referencing the collection name directly. Basically the whitelist would need to be:

1. Any future property/method on Apollo's DataSource class.
2. Any prop/method on this lib's class.
3. Any reserved/js class props (constructor?)

I was generating a few hundred/thousand random collections and saw this issue creeping in.

**Comment by sbrichardson** [comment]
To maintain compatibility, although messy, you could add the following (via es6 dynamic properties, not tested):

```
Starting with ECMAScript 2015, you can also use expressions for 
a computed property name to bind to the given function.
```

```js
get[!blacklist.includes(key)] () {
  return this.collection
}
```

**Comment by lorensr** [comment]
Replace with `this.collection` or `this.model` for mongoose: https://github.com/GraphQLGuide/apollo-datasource-mongodb/releases/tag/0.2.0
