### ISSUE TITLE
deleteFromCacheById does not clear DataLoader cache

### ISSUE THREAD

**Issue by ash0080** [GraphQLGuide/apollo-datasource-mongodb#44]
Today I found that I can't get the updated data with this package
In fact, I don't think this package currently works, plz check the comments I added

```js
const loader = new DataLoader(ids => {
const filter = {
  _id: {
	$in: ids  // <== ids = [ObjectId]
  }
}
const promise = model
  ? model.find(filter).exec()
  : collection.find(filter).toArray()

return promise.then(orderDocs(ids))
})

const cachePrefix = `mongo-${getCollection(collection).collectionName}-`

const methods = {
findOneById: async (id, { ttl } = {}) => {
  const key = cachePrefix + idToString(id)

  const cacheDoc = await cache.get(key)
  if (cacheDoc) {
	return EJSON.parse(cacheDoc)
  }

  const doc = await loader.load(id) // <== ids = [ObjectId]
  if (Number.isInteger(ttl)) {
	// https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-caching#apollo-server-caching
	cache.set(key, EJSON.stringify(doc), { ttl })
  }

  return doc
},
findManyByIds: (ids, { ttl } = {}) => {
  return Promise.all(ids.map(id => methods.findOneById(id, { ttl })))
},
deleteFromCacheById: async id => {
  const stringId = idToString(id)  // <== id = string??? can never delete a cache? because key is not a same thing
  loader.clear(stringId)
  await cache.delete(cachePrefix + stringId)
}
}

```

**Comment by ash0080** [comment]
yep, it is  confirmed, the keys are not the same thing,
In the current code, the key of the dataloader is always the ObjectID,
but you are trying to delete it with a string key. so it doesn't work

**Comment by lorensr** [comment]
DataLoader is separate from the cache. The cache is a key-value store, where the key is the `cachePrefix + stringId`. DataLoader deduplicates and batches using the ObjectId

**Comment by ash0080** [comment]
Please try it out yourself， I wrote a test, which has confirmed that the updated data cannot be retrieved without modifying the current code, because the key is used incorrectly。

**Comment by ash0080** [comment]
dataloader in your code now using ObjectID as keys, simply console.dir to check what exactly is stored in the cache

**Comment by lorensr** [comment]
Is there a way to modify this test to get it to fail?

https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/__tests__/cache.test.js#L101-L111

> Besides, I have a question, why use EJSON to store the data as string in cache? I don't understand, InMemoryLRUCache is a Map() actually, it can store anything, so why add this two-way conversion? This seems inefficient

The dev may be using a different cache. We need to match this signature:

![image](https://user-images.githubusercontent.com/251288/103329932-20404a00-4a2d-11eb-804d-16a309e92329.png)

**Comment by ash0080** [comment]
> Is there a way to modify this test to get it to fail?
> 
> https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/__tests__/cache.test.js#L101-L111
> 
> > Besides, I have a question, why use EJSON to store the data as string in cache? I don't understand, InMemoryLRUCache is a Map() actually, it can store anything, so why add this two-way conversion? This seems inefficient
> 
> The dev may be using a different cache. We need to match this signature:
> 
> ![image](https://user-images.githubusercontent.com/251288/103329932-20404a00-4a2d-11eb-804d-16a309e92329.png)

in your test you specify 'docs.id1._id'  is a string, try docs.id2._id

**Comment by lorensr** [comment]
Tests continue to pass after this commit:

https://github.com/GraphQLGuide/apollo-datasource-mongodb/commit/6ce707e458116477ef3935d4c440394b6a319339

**Comment by ash0080** [comment]
![截屏2020-12-30 下午12 55 53](https://user-images.githubusercontent.com/2803210/103331011-dee88280-4a9e-11eb-80f5-adac4eb885e0.png)

**Comment by 9at8** [comment]
@lorensr I think these two lines is where the problem stems from:

https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/cache.js#L43

The data loader stores an instance of `ObjectId`

https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/cache.js#L56

But we call clear with a `string`

The fix would be to convert `ObjectId` to string in both methods before calling methods on the data loader.

**Comment by ash0080** [comment]
@9at8 Yes, That's the issue exactly is.

Is there something wrong with my English? After communicating for so long, someone finally saw the point  :man_shrugging:

**Comment by lorensr** [comment]
Ah, I see. Thank you @ash0080 for reporting and @9at8 for clarifying! Fix released in https://github.com/GraphQLGuide/apollo-datasource-mongodb/releases/tag/0.2.11

Hopefully `0.2.11` works for you, @ash0080 ?

**Comment by ash0080** [comment]
Thanks, haven't tested it yet, but it should work, I've modified the local folk before and added some other features.

**Comment by ash0080** [comment]
Oh, yes, I forgot, the last question
According to the official documentation, the dataloader is supposed to be a per request cache, so how could this problem happen, shouldn't a new dataloader instance be generated for each request?

**Comment by lorensr** [comment]
Yes. A new instance is created each request if this library is used like this:

![image](https://user-images.githubusercontent.com/251288/103373229-59ff6800-4aa2-11eb-97b2-1dd5c163915b.png)

**Comment by 9at8** [comment]
Yes, a new dataloader is initialized on every request.

This is a problem when do the following in the same request:

1. Find a thing
2. Update it 
3. Find the same thing again later on

**Comment by ash0080** [comment]
I see, I was using dataSources incorrectly in my test (which was correct in the actual ApolloServer)
But by mistake I found a bug :smiley:
