### ISSUE TITLE
Using String id instead of ObjectId make it crash

### ISSUE THREAD

**Issue by Didier542** [GraphQLGuide/apollo-datasource-mongodb#47]
Hello, 

We have a MongoDB database using string ID's (no 12 bytes || 24 hex) Theses ID's were generated by MeteorJS.
We now develop a GraphQL layer with apollo server.

We want to use the apollo-datasource-mongodb to load our data but when we call the findOnebyId method we got this error :

`
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/app/node_modules/bson/lib/bson/objectid.js:59:11)
    at Function.ObjectID (/app/node_modules/bson/lib/bson/objectid.js:40:43)
    at file:///app/connectors/legacy.js:3:21
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
/app/node_modules/bson/lib/bson/objectid.js:59
`

It's because the module try to transform our string Id into a MongoDB ObjectId which is impossible with our current Id format.

After looking at the repo, [it seems that it can handle string Id](https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/index.d.ts)
`    
findOneById(
      id: ObjectId | **string**,
      options?: Options
    ): Promise<TData | null | undefined>
`

Our Users dataSource:
`
import { MongoDataSource } from 'apollo-datasource-mongodb'

export class Users extends MongoDataSource {
}
`

The initiation (context layer):
`
Users: new Users(legacy.collection('users'))
`

The call (model layer):
`async findOneById(obj, { id }, {dataSources: { Users }}) {
  return await Users.findOneById(id)
}
`

We don't use mongoose & typescript.

I don't find anywhere how I can handle this.

**Comment by Didier542** [comment]
Finally, I found where it crashes.
It can't handle string Id.
When I change stringToId to idToString, it works.

https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/fa186453dbba24f935013fb7097294c69ba4ce74/src/cache.js#L23

Is it possible to add an option to handle this ?

**Comment by lorensr** [comment]
Yes, I just published `v0.3.0`. Let me know if that works for you! ☺️

**Comment by Didier542** [comment]
Nice, it works well now, thanks a lot !
I will post another request soon to make it perfect 👍
