### ISSUE TITLE
Typescript Generic type error

### ISSUE THREAD

**Issue by stretch0** [GraphQLGuide/apollo-datasource-mongodb#49]
Trying to use `MongoDataSource` to extend my User dataSource class with typescript but seem to be getting the following error:

```
Generic type 'MongoDataSource<TData, TContext>' requires between 1 and 2 type arguments.ts(2707)
```

My User dataSrouce class is as so:
```
export default class Users extends MongoDataSource { }
```

How am I supposed to call `MongoDataSource` with 2 args when it's used to extend my own class?

**Comment by 9at8** [comment]
Hey @stretch0 ! Have you tried something like the example in the readme? https://github.com/GraphQLGuide/apollo-datasource-mongodb#typescript

Let me know if you have any other questions! 😀

**Comment by stretch0** [comment]
That has done the trick. 

Thanks for your help 😄
