### ISSUE TITLE
Supporting mongoose

### ISSUE THREAD

**Issue by emilmork** [GraphQLGuide/apollo-datasource-mongodb#5]
Have you an suggestion for how mongoose could be supported ?

I have tested with mongoose and it seams that the only issue is the `.toArray()` notation in cache.js. Mongoose is not using the native driver directly and the query result is not a cursor, like in mongodb native client.

I can make a PR with a suggestion but whanted to hear your thoughts first.

**Comment by ecerroni** [comment]
> Have you an suggestion for how mongoose could be supported ?
> 
> I have tested with mongoose and it seams that the only issue is the `.toArray()` notation in cache.js. Mongoose is not using the native driver directly and the query result is not a cursor, like in mongodb native client.
> 
> I can make a PR with a suggestion but wanted to hear your thoughts first.

I made a fork of this awesome package to extend the code and support both mongodb driver and mongoose:
https://github.com/ecerroni/apollo-datasource-mongodb

However, keep in mind that the API of my fork is not exactly the same as this one anymore and has started to diverge.

**Comment by emilmork** [comment]
@ecerroni Yes, i actually saw your repo one minute after I posted this question. I will look into it :)

**Comment by lorensr** [comment]
No suggestion, happy to look at a PR ☺️

**Comment by emilmork** [comment]
I have created a [PR](https://github.com/GraphQLGuide/apollo-datasource-mongodb/pull/6) with the same approach as in @ecerroni`s repo.

**Comment by emilmork** [comment]
@lorensr Do you publish the update to npm as well ? :)

**Comment by lorensr** [comment]
Published along with an API update: https://github.com/GraphQLGuide/apollo-datasource-mongodb/releases/tag/0.2.0
