### ISSUE TITLE
[QUESTION]: deleteFromCacheById doesn't work for findByFields

### ISSUE THREAD

**Issue by simplecommerce** [GraphQLGuide/apollo-datasource-mongodb#68]
Hi,

I haven't used it yet, but I noticed that `deleteFromCacheById` only works when used with `findOneById`.
In the code, it doesn't seem to work for `findByFields`.

Can you confirm?

**Comment by lorensr** [comment]
Confirmed. This is the key if you'd like to delete the cached results of `findByFields`:

https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/cache.js#L131

I'd also be happy to receive a PR for `deleteFromCacheByFields`.
