### ISSUE TITLE
(BUG) Cannot find module 'mongoose' or its corresponding type declarations. 

### ISSUE THREAD

**Issue by jake-ruth-qm** [GraphQLGuide/apollo-datasource-mongodb#87]
When trying to compile typescript, I get this error:

Cannot find module 'mongoose' or its corresponding type declarations. 

I tried rm -rf node_modules, package-lock.json, as well clean installing with yarn to see if that fixed it but no luck.

For now, I am just adding mongoose as a dev dep in my root package.json but I'd like if there is a solution for this.

I'm using the latest version (0.5.2) and tried downgrading as well. Still no luck.

**Comment by aymswick** [comment]
Bumping here as I ran into the issue as well, is this project still maintained? It seems mongoose should either be added to the package dependencies or the import removed

**Comment by lorensr** [comment]
Thanks for reporting! Seems a shame to move from devDep to dep for a compile-time thing, but I don't know of a better solution. Should be fixed in `0.5.3`.

I don't have much time these days, but intend to continue reviewing PRs.

**Comment by crccheck** [comment]
hah, of course you can't have it both ways. I found that `0.5.3` is introducing a second useless `mongoose@^5.13.8` dependency in my package in addition to my `mongoose@6.2.9`. I abandoned TypeScript so I don't have a solution for the original problem. Perhaps a peer dependency or optional dependency instead?

**Comment by lorensr** [comment]
Makes sense, sorry about that! Moved it to a peer dep in `0.5.4`—does that work for you?
